Added .editorconfig
iiitv/Odyssy pull request #154
Opened 2020-09-04 13:25 UTC by nlok5923

fixes : #143

2020-09-05 03:34 UTC, nlok5923 commented
@iiitv/project-maintainers please review this pr.

2020-09-05 03:45 UTC, aashutoshrathi requested changes
Just recheck and add only common things in `[*]`

2020-09-05 03:45 UTC, aashutoshrathi commented on .editorconfig
> +max_line_length = 119
The things you added in `[*]` are meant to be only for `[*.py]` right?
If so, better add them in `[*.py]`

2020-09-05 05:43 UTC, aashutoshrathi approved these changes
LGTM

2020-09-05 05:44 UTC, anshumanv approved these changes

2020-09-22 15:44 UTC, AmanRaj1608 commented
LGTM, merging

2020-09-22 15:44 UTC, merged